name: Auto-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
<<<<<<< HEAD
      run: make test_perimeter
    - name: Test
      run: ./test_perimeter
=======
      run: make test_area
    - name: Test
      run: ./test_area
>>>>>>> 816e529 (added workflow)

<<<<<<< area-ci
16
 
      run: make test_area
17
 
    - name: Test
18
 
      run: ./test_area
19
 
=======
20
 
      run: make test_perimeter
21
 
    - name: Test
22
 
      run: ./test_perimeter
23
 
>>>>>>> main
24
​
25
name: Auto-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: | 
        make test_area
        make test_perimeter
    - name: Test
      run: |
        ./test_area
        ./test_perimeter
